package com.test;
// Generated 30/03/2016 10:25:45 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actividades generated by hbm2java
 */
@Entity
@Table(name="ACTIVIDADES"
    ,schema="ANDRES"
)
public class Actividades  implements java.io.Serializable {


     private BigDecimal idactividad;
     private Tarea tarea;
     private String descripcion;
     private Double porcentaje;

    public Actividades() {
    }

	
    public Actividades(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }
    public Actividades(BigDecimal idactividad, Tarea tarea, String descripcion, Double porcentaje) {
       this.idactividad = idactividad;
       this.tarea = tarea;
       this.descripcion = descripcion;
       this.porcentaje = porcentaje;
    }
   
     @Id 

    
    @Column(name="IDACTIVIDAD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTAREA")
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="PORCENTAJE", precision=126, scale=0)
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }




}


