package com.test;
// Generated 30/03/2016 10:25:45 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name="TAREA"
    ,schema="ANDRES"
)
public class Tarea  implements java.io.Serializable {


     private BigDecimal idt;
     private BigDecimal usuario;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Actividades> actividades = new HashSet<Actividades>(0);

    public Tarea() {
    }

	
    public Tarea(BigDecimal idt) {
        this.idt = idt;
    }
    public Tarea(BigDecimal idt, BigDecimal usuario, String descripcion, Date fechaInicio, Date fechaFin, Set<Actividades> actividades) {
       this.idt = idt;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.actividades = actividades;
    }
   
     @Id 

    
    @Column(name="IDT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdt() {
        return this.idt;
    }
    
    public void setIdt(BigDecimal idt) {
        this.idt = idt;
    }

    
    @Column(name="USUARIO", precision=20, scale=0)
    public BigDecimal getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(BigDecimal usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", length=7)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarea")
    public Set<Actividades> getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Set<Actividades> actividades) {
        this.actividades = actividades;
    }

 


}


