package com.test;
// Generated 30/03/2016 10:25:45 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="ANDRES"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String telefono;
     private String direccion;

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String nombre, String telefono, String dir) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = dir;
    }
    
    @Id 
    @Column(name="IDUSUARIO", unique=true, nullable=false, precision=22, scale=0)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    
    
    @Column(name="NOMBRE", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    @Column(name="TELEFONO", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

     @Column(name="DIRECCION", length=40)
    public String getDireccion() {
        return this.telefono;
    }
    
    public void setDireccion(String direc) {
        this.direccion = direc;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idusuario=" + idusuario + ", nombre=" + nombre + ", telefono=" + telefono + ", direccion=" + direccion + '}';
    }



}


